### ISSUE TITLE
Remove the "Go" button for filtering entries

### ISSUE THREAD

**Issue by dragansah** [bobharner/ComponentWorld#12]
Basically, the form submission should be on change event on the "checklist" and the "select" components.

**Comment by dragansah** [comment]
Bob, what do you think?

I have a working commit where I replaced

onclick="this.form.performSubmit()" (this Programmatically perform a submit, invoking the onsubmit event handler (if present) before calling form.submit().)

with

onclick="this.form.fire(Tapestry.FORM_PROCESS_SUBMIT_EVENT)"

**Comment by bobharner** [comment]
Looks good.
